# Generated by Django 3.1.5 on 2021-01-18 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='user_id',
            new_name='user',
        ),
    ]
