# Generated by Django 3.1.5 on 2021-01-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210114_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='commit_count',
            new_name='comment_count',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.ImageField(null=True, upload_to='product/%Y-%m-%d', verbose_name='图片'),
        ),
    ]
